//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MejjHonda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEJJ_FacturaDeta
    {
        public int IdFacturaD { get; set; }
        public int IdFacturaE { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> PorcentajeDesc { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
    
        public virtual MEJJ_Articulo MEJJ_Articulo { get; set; }
        public virtual MEJJ_FacturaEnca MEJJ_FacturaEnca { get; set; }
    }
}
