//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MejjHonda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MejjHondaEntities : DbContext
    {
        public MejjHondaEntities()
            : base("name=MejjHondaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MEJJ_Articulo> MEJJ_Articulo { get; set; }
        public virtual DbSet<MEJJ_Cliente> MEJJ_Cliente { get; set; }
        public virtual DbSet<MEJJ_Empleado> MEJJ_Empleado { get; set; }
        public virtual DbSet<MEJJ_FacturaDeta> MEJJ_FacturaDeta { get; set; }
        public virtual DbSet<MEJJ_FacturaEnca> MEJJ_FacturaEnca { get; set; }
        public virtual DbSet<MEJJ_Moneda> MEJJ_Moneda { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
