//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MejjHonda.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MEJJ_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEJJ_Articulo()
        {
            this.MEJJ_FacturaDeta = new HashSet<MEJJ_FacturaDeta>();
        }
    
        public int IdArticulo { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DisplayName("Descripción")]
        [StringLength(100, ErrorMessage = "Máximo 100 dígitos")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DisplayName("Modelo")]
        [StringLength(50, ErrorMessage = "Máximo 10 dígitos")]
        public string Modelo { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Solo números")]
        public Nullable<decimal> Precio { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [StringLength(10, ErrorMessage = "Máximo 10 dígitos")]
        public string Color { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DisplayName("Tamaño")]
        [Range(0, int.MaxValue, ErrorMessage = "Sólo números")]
        public string Tamanio { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEJJ_FacturaDeta> MEJJ_FacturaDeta { get; set; }
    }
}
