//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MejjHonda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MEJJ_FacturaEnca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEJJ_FacturaEnca()
        {
            this.MEJJ_FacturaDeta = new HashSet<MEJJ_FacturaDeta>();
        }
    
        public int IdFacturaE { get; set; }
        public int IdEmpleado { get; set; }
        public int IdCliente { get; set; }
        public string Tipo { get; set; }
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaIng { get; set; }
        public string Observacion { get; set; }
        public string MedioPago { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public int IdMoneda { get; set; }
    
        public virtual MEJJ_Cliente MEJJ_Cliente { get; set; }
        public virtual MEJJ_Empleado MEJJ_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEJJ_FacturaDeta> MEJJ_FacturaDeta { get; set; }
        public virtual MEJJ_Moneda MEJJ_Moneda { get; set; }
    }
}
