//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MejjHonda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MEJJ_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEJJ_Empleado()
        {
            this.MEJJ_FacturaEnca = new HashSet<MEJJ_FacturaEnca>();
        }
    
        public int IdEmpleado { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [StringLength(15, ErrorMessage = "Maximo 15 digitos")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [Range(0, int.MaxValue, ErrorMessage = "Solo numeros")]
        [DisplayName("Cédula")]
        public string Cedula { get; set; }
        [EmailAddress(ErrorMessage = "Formato de correo invalido")]
        [StringLength(20, ErrorMessage = "Maximo 20 digitos")]
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DisplayName("e-mail")]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DataType(DataType.PhoneNumber)]
        [Range(0, int.MaxValue, ErrorMessage = "Solo numeros")]
        [DisplayName("Teléfono")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DisplayName("Dirección ")]
        [StringLength(70, ErrorMessage = "Maximo 70 digitos")]
        public string Direccion { get; set; }
        public Nullable<int> IdRol { get; set; }
        [Required(ErrorMessage = "Este campo es nesesario")]
        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        public string Contraseña { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEJJ_FacturaEnca> MEJJ_FacturaEnca { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
